"""test

Revision ID: b50da25d899c
Revises: e09f427cba64
Create Date: 2025-08-17 13:34:47.581091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50da25d899c'
down_revision: Union[str, Sequence[str], None] = 'e09f427cba64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('users', sa.Column('test', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE users SET test = true WHERE test IS NULL")

    # Now make the column NOT NULL
    op.alter_column('users', 'test', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###
